---

services:
  #- core.harbor.cloud.prz/infra/docker:dind
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2376" # for default docker image for docker hub
  # DOCKER_HOST: "tcp://core.harbor.cloud.prz-infra-docker:2376" # use this for our custom image from harbor
  # DOCKER_HOST: "tcp://localhost:2376"
  DOCKER_TLS_VERIFY: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  # service docker:dind container settings:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_PATH: "/certs/client"
  #DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  #FF_RESOLVE_FULL_TLS_CHAIN: "true"
  EARTHLY_PUSH: "true"
  
  #KUBERNETES_CPU_REQUEST: "3"
  #KUBERNETES_CPU_LIMIT: "5"
  #KUBERNETES_MEMORY_REQUEST: "2Gi"
  #KUBERNETES_MEMORY_LIMIT: "4Gi"
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: "4Gi"
  KUBERNETES_EPHEMERAL_STORAGE_LIMIT: "6Gi"

  #KUBERNETES_HELPER_CPU_REQUEST: "3"
  #KUBERNETES_HELPER_CPU_LIMIT: "5"
  #KUBERNETES_HELPER_MEMORY_REQUEST: "2Gi"
  #KUBERNETES_HELPER_MEMORY_LIMIT: "4Gi"
  KUBERNETES_HELPER_EPHEMERAL_STORAGE_REQUEST: "4Gi"
  KUBERNETES_HELPER_EPHEMERAL_STORAGE_LIMIT: "6Gi"

  #KUBERNETES_SERVICE_CPU_REQUEST: "10"
  #KUBERNETES_SERVICE_CPU_LIMIT: "12"
  #KUBERNETES_SERVICE_MEMORY_REQUEST: "60Gi"
  #KUBERNETES_SERVICE_MEMORY_LIMIT: "80Gi"
  KUBERNETES_SERVICE_EPHEMERAL_STORAGE_REQUEST: "4Gi"
  KUBERNETES_SERVICE_EPHEMERAL_STORAGE_LIMIT: "6Gi"

image: earthly/earthly:v0.8.4

before_script:
  - mkdir /root/.docker
  - cp /certs/client/*.pem /root/.docker/
  # wait for dockerd on runner pod's svc-0 container 
  - until docker info >/dev/null; do sleep 1; done
  #- earthly --verbose sat ls
  - earthly bootstrap
  # debug:
  - echo "$HARBOR_OCI -- $HARBOR_HOST -- $HARBOR_URL"
  #- "${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
  - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST

earthly:
  tags:
    - earthly
  stage: build
  script:
    #- sleep 1h
    # configure smaller cache (TODO: find a way how to change path where earthly-cache is located, which is /var/lib/docker/volumes/earthly-cache by default under "scripts" mount, or find a way how to define the "scripts" volume under a different type as CSI)
    - earthly config global.cache_size_mb 2000
    - earthly --no-cache --verbose --ci --push -P +images --RELEASE="2023.2"
    #- earthly --verbose --ci --push -P +images
