---

services:
  #- core.harbor.cloud.prz/infra/docker:dind
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2376" # for default docker image for docker hub
  # DOCKER_HOST: "tcp://core.harbor.cloud.prz-infra-docker:2376" # use this for our custom image from harbor
  # DOCKER_HOST: "tcp://localhost:2376"
  DOCKER_TLS_VERIFY: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  # service docker:dind container settings:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_PATH: "/certs/client"
  #DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  #FF_RESOLVE_FULL_TLS_CHAIN: "true"
  EARTHLY_PUSH: "true"

image: earthly/earthly:v0.8.4

before_script:
  - mkdir /root/.docker
  - cp /certs/client/*.pem /root/.docker/
  # wait for dockerd on runner pod's svc-0 container 
  - until docker info >/dev/null; do sleep 1; done
  #- earthly --verbose sat ls
  - earthly bootstrap
  # debug:
  - echo "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  #- "${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $HARBOR_HOST

earthly:
  tags:
    - earthly
  stage: build
  script:
    #- sleep 1h
    - earthly --verbose --ci --push -P +images --RELEASE="2023.2"
    #- earthly --verbose --ci --push -P +images
