---

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  #DOCKER_TLS_CERTDIR: "/certs"

image: earthly/earthly:v0.8.4

before_script:
  - earthly bootstrap --verbose
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

script:
  - cp /home/gitlab-runner/.gitlab-runner/certs/gitlab.cloud.prz.crt /usr/local/share/ca-certificates/
  - update-ca-certificates

earthly:
  tags:
    - earthly
  stage: build
  script:
    - earthly --ci --push -P +images
