---

stages:
  - build

build_image:
  stage: build
  tags:
    - image-builder-vm-local
  script:
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" "$HARBOR_HOST"
    - docker buildx bake --push
