---

services:
  - docker:dind
  #- docker:stable

variables:
  DOCKER_HOST: "tcp://docker:2376"
  DOCKER_TLS_VERIFY: 1
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  # service docker:dind container settings:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_PATH: "/certs/client"
  #DOCKER_TLS_CERTDIR: ""

image: earthly/earthly:v0.8.4

before_script:
  # install PRZ CA chain
  - cp /etc/ssl/certs/prz_ca_bundle.crt /usr/local/share/ca-certificates/
  ##- cp /home/gitlab-runner/.gitlab-runner/certs/prz-ca-fullchain/ca.crt /usr/local/share/ca-certificates/
  #- cp /etc/ssl/certs/prz_ca_bundle.crt /usr/local/share/ca-certificates/
  - update-ca-certificates
  # copy PRZ CA certificate to docker's config directory; TODO: instead change the path to /home/gitlab-runner/.gitlab-runner/certs/prz-ca-fullchain/ca.crt for CA in earthly's docker command? 
  - mkdir /root/.docker
  #- cp /etc/ssl/certs/prz_ca_bundle.crt /root/.docker/ca.pem
  - cp /etc/ssl/certs/prz_ca_bundle.crt /root/.docker/ca.pem
  ##- cp /home/gitlab-runner/.gitlab-runner/certs/prz-ca-fullchain/ca.crt /root/.docker/ca.pem
  #- ps aux
  #- docker-machine regenerate-certs default
  - earthly --verbose sat ls
  - earthly --verbose bootstrap
  #- until docker info; do sleep 1; done
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

earthly:
  tags:
    - earthly
  stage: build
  script:
    - earthly --ci --push -P +images
