VERSION 0.7

ARG --global PROJECT=nova
ARG --global RELEASE=2024.1
ARG --global PROJECT_REF=11301e7e3f0d81a3368632f90608e30d9c647111

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES="python-barbicanclient"

platform-image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "ceph-common genisoimage iproute2 libosinfo-bin lsscsi ndctl nvme-cli openssh-client ovmf python3-libvirt python3-rados python3-rbd qemu-efi-aarch64 qemu-utils sysfsutils udev util-linux apache2 libapache2-mod-wsgi-py3 cryptsetup net-tools openssh-server"
  GIT CLONE --branch v1.4.0 https://github.com/novnc/noVNC.git /usr/share/novnc
  ARG REGISTRY=core.harbor.cloud.prz/openstack-helm
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}

image:
  BUILD --platform linux/amd64 +platform-image
