VERSION 0.7

ARG --global PROJECT=glance
ARG --global RELEASE=2024.1
ARG --global PROJECT_REF=b5b29a0ae15d44424f04db0686328d0a01a14853

build.plugin:
  ARG PLUGIN
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+GIT_CHECKOUT \
    --PROJECT=${PLUGIN} \
    --PROJECT_REF=stable/${RELEASE}
  SAVE ARTIFACT /src

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  COPY (+build.plugin/src --PLUGIN=glance_store) /glance_store
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES="/glance_store[cinder] os-brick==6.9.0 oslo.rootwrap python-swiftclient python-cinderclient"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  COPY ../kubernetes+image/kubectl /usr/local/bin/kubectl
  DO ../+APT_INSTALL \
    --PACKAGES "ceph-common lsscsi nvme-cli python3-rados python3-rbd qemu-utils sysfsutils udev util-linux"
  ARG REGISTRY=core.harbor.cloud.prz/openstack-helm
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
