VERSION 0.7

ARG --global PROJECT=cinder
ARG --global RELEASE=2024.1
ARG --global PROJECT_REF=db98dc207060da234c32a563c13cac1edbd62952

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES="purestorage python-swiftclient"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  COPY ../kubernetes+image/kubectl /usr/local/bin/kubectl
  DO ../+APT_INSTALL \
    --PACKAGES "ceph-common lsscsi nvme-cli python3-rados python3-rbd qemu-utils sysfsutils udev util-linux cryptsetup apache2 libapache2-mod-wsgi-py3"
  ARG REGISTRY=core.harbor.cloud.prz/openstack-helm
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
