VERSION 0.7

ARG --global PROJECT=horizon
ARG --global RELEASE=2024.1
ARG --global PROJECT_REF=dcaf0cc51fe998ca6de89a82a3cdadd26131830b

build.plugin:
  ARG PLUGIN
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  DO ../openstack-service+GIT_CHECKOUT \
    --PROJECT=${PLUGIN} \
    --PROJECT_REF=stable/${RELEASE}
  SAVE ARTIFACT /src

build:
  FROM ../openstack-service+builder --RELEASE=${RELEASE}
  COPY (+build.plugin/src --PLUGIN=designate-dashboard) /designate-dashboard
  COPY (+build.plugin/src --PLUGIN=heat-dashboard) /heat-dashboard
  COPY (+build.plugin/src --PLUGIN=magnum-ui) /magnum-ui
  COPY (+build.plugin/src --PLUGIN=manila-ui) /manila-ui
  COPY (+build.plugin/src --PLUGIN=neutron-vpnaas-dashboard) /neutron-vpnaas-dashboard
  COPY (+build.plugin/src --PLUGIN=octavia-dashboard) /octavia-dashboard
  DO ../openstack-service+BUILD_VENV \
    --PROJECT=${PROJECT} \
    --PROJECT_REF=${PROJECT_REF} \
    --PIP_PACKAGES "/designate-dashboard /heat-dashboard /magnum-ui /neutron-vpnaas-dashboard /octavia-dashboard /manila-ui pymemcache"

image:
  FROM ../openstack-service+image --RELEASE ${RELEASE} --PROJECT ${PROJECT}
  COPY +build/venv /var/lib/openstack
  DO ../+APT_INSTALL \
    --PACKAGES "apache2 gettext libapache2-mod-wsgi-py3"
  ARG REGISTRY=core.harbor.cloud.prz/openstack-helm
  SAVE IMAGE --push \
    ${REGISTRY}/${PROJECT}:${RELEASE} \
    ${REGISTRY}/${PROJECT}:${PROJECT_REF}
